version: "3"

services:
  docs:
    build: .
    image: loehj/software-quality
    restart: always
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"

networks:
  default:
    name: nginx-proxy
    external: true
