name: CD
on:
  push:
    branches: [main, dev]
    paths: ["src/**", ".github/workflows/cd.yml"]
  workflow_dispatch:

jobs:
  frontend_build:
    name: Build (Frontend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"
      - name: Install node modules
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: frontend_build
          path: frontend/dist

  backend_build:
    name: Build (Backend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"
      - name: Install node modules
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: backend_build
          path: backend/dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ["frontend_build", "backend_build"]
    steps:
      - run: echo "Noop"

  deploy_check:
    name: Check deployment
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - run: echo "Noop"
