name: CD
on:
  push:
    branches: [main]
    paths: ["src/**", ".github/workflows/cd.yml"]
  workflow_dispatch:

jobs:
  frontend_build:
    name: Build (Frontend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"
      - name: Install node modules
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: frontend_build
          path: dist

  frontend_unit_tests:
    name: Unit tests (Frontend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"
      - name: Install node modules
        run: npm ci
      - name: Run unit tests
        run: npm run test:unit

  frontend_integration_tests:
    name: Integration tests (Frontend)
    runs-on: ubuntu-latest
    needs: frontend_build
    steps:
      - run: echo "Noop"

  backend_build:
    name: Build (Backend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"
      - name: Install node modules
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: backend_build
          path: dist

  backend_unit_tests:
    name: Unit tests (Backend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"
      - name: Install node modules
        run: npm ci
      - name: Run unit tests
        run: npm run test:unit

  backend_integration_tests:
    name: Integration tests (Backend)
    runs-on: ubuntu-latest
    needs: backend_build
    steps:
      - run: echo "Noop"

  system_tests:
    name: System tests
    runs-on: ubuntu-latest
    needs:
      [
        "frontend_unit_tests",
        "frontend_integration_tests",
        "backend_unit_tests",
        "backend_integration_tests",
      ]
    steps:
      - run: echo "Noop"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: system_tests
    steps:
      - run: echo "Noop"

  deploy_check:
    name: Check deployment
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - run: echo "Noop"
