name: CD
on:
  push:
    branches: [main, dev, qa]
    paths: ["docs/**"]
  workflow_dispatch:

jobs:
  frontend_build:
    name: Build (Frontend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install node modules
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: frontend_build
          path: docs/.vitepress/dist

  backend_build:
    name: Build (Backend)
    runs-on: ubuntu-latest
    steps:
      - run: echo "Noop"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ["frontend_build", "backend_build"]
    steps:
      - run: echo "Noop"

  deploy_verify:
    name: Verify deployment
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - run: echo "Noop"
