name: CI
on:
  pull_request:
    branches: [main, beta]
    paths: ["src/**"]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install node modules
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm run test:unit
      # TODO: add linting
      - name: Check test coverage
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "90"
          filename: "coverage/clover.xml"
