name: CI
on:
  pull_request:
    branches: [main, dev, qa]
    paths: ["docs/**"]
  workflow_dispatch:

jobs:
  frontend_build:
    name: Build (Frontend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install node modules
        run: npm ci
      - name: Build
        run: npm run docs:build

  frontend_unit_tests:
    name: Unit tests (Frontend)
    runs-on: ubuntu-latest
    steps:
      - run: echo "Noop"

  frontend_integration_tests:
    name: Integration tests (Frontend)
    runs-on: ubuntu-latest
    needs: frontend_build
    steps:
      - run: echo "Noop"

  backend_build:
    name: Build (Backend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - run: echo "Noop"

  backend_unit_tests:
    name: Unit tests (Backend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - run: echo "Noop"

  backend_integration_tests:
    name: Integration tests (Backend)
    runs-on: ubuntu-latest
    needs: backend_build
    steps:
      - run: echo "Noop"

  system_tests:
    name: System tests
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs:
      [
        "frontend_unit_tests",
        "frontend_integration_tests",
        "backend_unit_tests",
        "backend_integration_tests",
      ]
    steps:
      - run: echo "Noop"
